def personal_sum(*numbers):
    result = 0
    incorrect_data = 0
    for num in numbers:
        count = len(num) - incorrect_data
        for i in num:
            try:
                result += i
            except TypeError:
                print(f'В numbers записан некорректный тип данных - {i}')
                incorrect_data += 1          
    return result, count, incorrect_data

def calculate_average(*numbers):
    try:
        sum_ = personal_sum(*numbers)
        average = sum_[0] / sum_[1]
        return average
    except TypeError:
        return None
    except ZeroDivisionError:
      return 0
      
      
#print(personal_sum([2, 2, 3, 4, 'прив']))
#print(calculate_average())

#print(f'Результат 1: {calculate_average("1, 2, 3")}') # Строка перебирается, но каждый символ - строковый тип
#print(f'Результат 2: {calculate_average([1, "Строка", 3, "Ещё Строка"])}') # Учитываются только 1 и 3
#print(f'Результат 3: {calculate_average(567)}') # Передана не коллекция
#prisnt(f'Результат 4: {calculate_average([42, 15, 36, 13])}') # Всё должно работать
